import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClientProvider } from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "othello2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProvider>
      <html lang="ja">
        <body className={inter.className}>{children}</body>
      </html>
    </ClientProvider>
  );
}
